export type ChartKind = 'bar' | 'area' | 'line' | 'horizontal' | 'pie' | 'grouped'
export type ChartUnit = 'percent' | 'dollars' | 'score' | 'hours' | 'rating' | 'count'

export type ChartTemplate = {
  title: string
  subtitle: string
  labels: string[]
  /** Primary series baseline values */
  bases: number[]
  /** Optional second series for grouped/compare charts */
  bases2?: number[]
  chartKind: ChartKind
  unit: ChartUnit
  /** Realistic data shape */
  pattern: 'growth' | 'decline' | 'peak' | 'volatile' | 'ranked' | 'share'
  topics?: string[]
}

/** Industry-realistic chart templates - each article picks a unique subset via slug hash */
export const CHART_CATALOG: ChartTemplate[] = [
  // CRM
  {
    title: 'CRM adoption by sales team size',
    subtitle: 'Percentage of teams with an active CRM in 2025',
    labels: ['1–10 reps', '11–25', '26–50', '51–100', '100+'],
    bases: [34, 48, 67, 81, 93],
    chartKind: 'bar',
    unit: 'percent',
    pattern: 'growth',
    topics: ['crm'],
  },
  {
    title: 'HubSpot vs Salesforce market preference',
    subtitle: 'Buyer shortlist rate among SMB teams (50–500 employees)',
    labels: ['HubSpot', 'Salesforce', 'Pipedrive', 'Zoho', 'Other'],
    bases: [38, 31, 14, 11, 6],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
    topics: ['crm'],
  },
  {
    title: 'Sales pipeline visibility improvement',
    subtitle: 'Weeks after CRM go-live - forecast accuracy gains',
    labels: ['Week 2', 'Week 4', 'Week 8', 'Week 12', 'Week 16'],
    bases: [12, 24, 41, 58, 71],
    chartKind: 'area',
    unit: 'percent',
    pattern: 'growth',
    topics: ['crm'],
  },
  {
    title: 'CRM feature priority scores',
    subtitle: 'What buyers rank highest during vendor evaluation',
    labels: ['Pipeline', 'Email sync', 'Reporting', 'Mobile', 'AI assist'],
    bases: [88, 79, 74, 62, 55],
    chartKind: 'horizontal',
    unit: 'score',
    pattern: 'ranked',
    topics: ['crm'],
  },
  {
    title: 'Lead response time - before vs after CRM',
    subtitle: 'Average hours to first contact (lower is better)',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    bases: [18, 14, 11, 9, 8],
    bases2: [42, 38, 35, 40, 36],
    chartKind: 'grouped',
    unit: 'hours',
    pattern: 'decline',
    topics: ['crm'],
  },
  // VoIP / Call center
  {
    title: 'VoIP migration cost savings timeline',
    subtitle: 'Monthly telecom spend vs legacy PBX baseline',
    labels: ['Month 1', 'Month 3', 'Month 6', 'Month 9', 'Month 12'],
    bases: [8, 19, 28, 35, 41],
    chartKind: 'line',
    unit: 'percent',
    pattern: 'growth',
    topics: ['voip'],
  },
  {
    title: 'Cloud call center uptime benchmarks',
    subtitle: 'Provider SLA achievement across top 5 platforms',
    labels: ['RingCentral', '8x8', 'Dialpad', 'Nextiva', 'Vonage'],
    bases: [99.99, 99.97, 99.95, 99.94, 99.92],
    chartKind: 'horizontal',
    unit: 'rating',
    pattern: 'ranked',
    topics: ['voip'],
  },
  {
    title: 'Per-seat VoIP pricing comparison',
    subtitle: 'Average all-in monthly cost per user (USD)',
    labels: ['Basic', 'Standard', 'Pro', 'Enterprise'],
    bases: [22, 35, 48, 72],
    chartKind: 'bar',
    unit: 'dollars',
    pattern: 'growth',
    topics: ['voip'],
  },
  {
    title: 'Call volume handled by AI vs agents',
    subtitle: 'Contact center tier-1 resolution split',
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    bases: [22, 31, 44, 52],
    bases2: [78, 69, 56, 48],
    chartKind: 'grouped',
    unit: 'percent',
    pattern: 'growth',
    topics: ['voip'],
  },
  {
    title: 'Average hold time reduction post-migration',
    subtitle: 'Minutes per inbound call - cloud vs on-prem',
    labels: ['Retail', 'Healthcare', 'Finance', 'SaaS', 'Logistics'],
    bases: [2.1, 3.4, 2.8, 1.9, 2.6],
    bases2: [5.8, 7.2, 6.1, 4.9, 5.4],
    chartKind: 'grouped',
    unit: 'hours',
    pattern: 'decline',
    topics: ['voip'],
  },
  // HR / Payroll
  {
    title: 'Global payroll error rate decline',
    subtitle: 'Errors per 1,000 pay runs after automation',
    labels: ['Manual', 'Month 3', 'Month 6', 'Month 12', 'Month 18'],
    bases: [48, 32, 18, 9, 4],
    chartKind: 'area',
    unit: 'count',
    pattern: 'decline',
    topics: ['hr'],
  },
  {
    title: 'HR software ROI by company size',
    subtitle: 'Months to break even on platform investment',
    labels: ['1–50', '51–200', '201–500', '501–1000', '1000+'],
    bases: [4, 7, 11, 14, 18],
    chartKind: 'bar',
    unit: 'count',
    pattern: 'growth',
    topics: ['hr'],
  },
  {
    title: 'Employee self-service adoption',
    subtitle: 'Portal usage rate within first 90 days',
    labels: ['Pay stubs', 'PTO requests', 'Benefits', 'Tax forms', 'Profile'],
    bases: [94, 87, 72, 68, 81],
    chartKind: 'horizontal',
    unit: 'percent',
    pattern: 'ranked',
    topics: ['hr'],
  },
  {
    title: 'Payroll processing time saved',
    subtitle: 'Hours per pay cycle - before vs after HRIS',
    labels: ['Bi-weekly', 'Semi-monthly', 'Monthly'],
    bases: [3.5, 4.2, 6.8],
    bases2: [14, 16, 22],
    chartKind: 'grouped',
    unit: 'hours',
    pattern: 'decline',
    topics: ['hr'],
  },
  {
    title: 'Remote workforce HR tool usage',
    subtitle: 'Feature engagement among distributed teams',
    labels: ['2022', '2023', '2024', '2025'],
    bases: [41, 58, 74, 89],
    chartKind: 'line',
    unit: 'percent',
    pattern: 'growth',
    topics: ['hr'],
  },
  // Fleet / GPS
  {
    title: 'Fleet fuel efficiency gains',
    subtitle: 'MPG improvement after GPS route optimization',
    labels: ['Week 1', 'Week 4', 'Week 8', 'Week 12'],
    bases: [0, 6, 11, 15],
    chartKind: 'line',
    unit: 'percent',
    pattern: 'growth',
    topics: ['fleet'],
  },
  {
    title: 'Idle time reduction by vehicle type',
    subtitle: 'Average daily idle minutes cut with telematics',
    labels: ['Vans', 'Trucks', 'Cars', 'Heavy equip.'],
    bases: [32, 28, 24, 19],
    chartKind: 'bar',
    unit: 'percent',
    pattern: 'ranked',
    topics: ['fleet'],
  },
  {
    title: 'GPS fleet software market share',
    subtitle: 'Enterprise buyer selection frequency',
    labels: ['Samsara', 'Geotab', 'Verizon Connect', 'Fleet Complete', 'Other'],
    bases: [28, 24, 18, 12, 18],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
    topics: ['fleet'],
  },
  {
    title: 'Maintenance cost avoidance',
    subtitle: 'Preventive alerts vs reactive repairs (USD/month per vehicle)',
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    bases: [180, 210, 245, 260, 290, 310],
    chartKind: 'area',
    unit: 'dollars',
    pattern: 'growth',
    topics: ['fleet'],
  },
  {
    title: 'Driver safety score improvement',
    subtitle: 'Average fleet safety index over 6 months',
    labels: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6'],
    bases: [62, 68, 73, 78, 82, 86],
    chartKind: 'area',
    unit: 'score',
    pattern: 'growth',
    topics: ['fleet'],
  },
  // AI
  {
    title: 'AI agent ticket deflection rate',
    subtitle: 'Tier-1 support handled without human handoff',
    labels: ['Pilot', 'Month 1', 'Month 3', 'Month 6'],
    bases: [18, 32, 48, 58],
    chartKind: 'line',
    unit: 'percent',
    pattern: 'growth',
    topics: ['ai'],
  },
  {
    title: 'AI automation maturity distribution',
    subtitle: 'Where mid-market teams are in their AI journey',
    labels: ['Exploring', 'Piloting', 'Scaling', 'Optimized'],
    bases: [35, 38, 19, 8],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
    topics: ['ai'],
  },
  {
    title: 'Response time - AI vs human agents',
    subtitle: 'Average first response in seconds',
    labels: ['Email', 'Chat', 'Social', 'Phone'],
    bases: [2.1, 1.4, 3.2, 8.5],
    bases2: [4.2, 2.8, 6.1, 45],
    chartKind: 'grouped',
    unit: 'hours',
    pattern: 'decline',
    topics: ['ai'],
  },
  {
    title: 'AI agent ROI breakeven timeline',
    subtitle: 'Months to positive ROI by use case',
    labels: ['Support', 'Sales', 'Ops', 'HR', 'Finance'],
    bases: [5, 7, 9, 11, 8],
    chartKind: 'horizontal',
    unit: 'count',
    pattern: 'ranked',
    topics: ['ai'],
  },
  {
    title: 'LLM-powered workflow adoption',
    subtitle: 'Teams deploying AI agents in production',
    labels: ['2023', '2024', '2025', '2026E'],
    bases: [12, 28, 47, 68],
    chartKind: 'bar',
    unit: 'percent',
    pattern: 'growth',
    topics: ['ai'],
  },
  // Marketing
  {
    title: 'Email marketing ROI by industry',
    subtitle: 'Return per $1 spent - benchmark averages',
    labels: ['Retail', 'B2B SaaS', 'Healthcare', 'Finance', 'Nonprofit'],
    bases: [42, 36, 28, 38, 45],
    chartKind: 'bar',
    unit: 'dollars',
    pattern: 'volatile',
    topics: ['marketing'],
  },
  {
    title: 'Marketing automation adoption curve',
    subtitle: 'SMB teams using 2+ integrated marketing tools',
    labels: ['2020', '2021', '2022', '2023', '2024', '2025'],
    bases: [22, 31, 42, 54, 67, 78],
    chartKind: 'area',
    unit: 'percent',
    pattern: 'growth',
    topics: ['marketing'],
  },
  {
    title: 'MarTech stack consolidation trend',
    subtitle: 'Average number of point tools per marketing team',
    labels: ['2021', '2022', '2023', '2024', '2025'],
    bases: [14, 12, 10, 8, 6],
    chartKind: 'line',
    unit: 'count',
    pattern: 'decline',
    topics: ['marketing'],
  },
  // Finance / ERP
  {
    title: 'Invoice processing time reduction',
    subtitle: 'Days from receipt to approval - AP automation impact',
    labels: ['Before', '30 days', '60 days', '90 days', '180 days'],
    bases: [12.4, 8.2, 5.1, 3.2, 1.8],
    chartKind: 'area',
    unit: 'count',
    pattern: 'decline',
    topics: ['finance'],
  },
  {
    title: 'Accounting software feature priorities',
    subtitle: 'Buyer ranking during evaluation (score out of 100)',
    labels: ['Reporting', 'Invoicing', 'Bank sync', 'Multi-entity', 'Tax prep'],
    bases: [91, 84, 79, 62, 71],
    chartKind: 'horizontal',
    unit: 'score',
    pattern: 'ranked',
    topics: ['finance'],
  },
  {
    title: 'Month-end close duration',
    subtitle: 'Business days to close books - automated vs manual',
    labels: ['Startup', 'SMB', 'Mid-market', 'Enterprise'],
    bases: [3, 5, 8, 12],
    bases2: [8, 12, 18, 25],
    chartKind: 'grouped',
    unit: 'count',
    pattern: 'decline',
    topics: ['finance'],
  },
  // General / cross-topic (large pool for variety)
  {
    title: 'Software evaluation timeline',
    subtitle: 'Average weeks from research to purchase decision',
    labels: ['Simple SaaS', 'CRM/ERP', 'Security', 'Custom build'],
    bases: [3, 8, 12, 24],
    chartKind: 'bar',
    unit: 'count',
    pattern: 'ranked',
  },
  {
    title: 'Buyer research sources used',
    subtitle: 'Where teams gather vendor information first',
    labels: ['Review sites', 'Peer refs', 'Vendor site', 'Analyst', 'Social'],
    bases: [34, 28, 18, 12, 8],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
  },
  {
    title: 'Implementation success rate',
    subtitle: 'Projects meeting timeline and budget targets',
    labels: ['Q1', 'Q2', 'Q3', 'Q4'],
    bases: [58, 62, 67, 71],
    chartKind: 'line',
    unit: 'percent',
    pattern: 'growth',
  },
  {
    title: 'Total cost of ownership - year 1 vs year 3',
    subtitle: 'Software spend as % of initial license (TCO index)',
    labels: ['CRM', 'HRIS', 'VoIP', 'ERP', 'Marketing'],
    bases: [142, 128, 115, 168, 135],
    bases2: [185, 162, 138, 224, 178],
    chartKind: 'grouped',
    unit: 'percent',
    pattern: 'growth',
  },
  {
    title: 'Integration complexity scores',
    subtitle: 'IT hours required for typical go-live',
    labels: ['Native API', 'Zapier', 'Custom ETL', 'Manual CSV'],
    bases: [12, 24, 80, 40],
    chartKind: 'horizontal',
    unit: 'hours',
    pattern: 'ranked',
  },
  {
    title: 'Vendor satisfaction ratings',
    subtitle: 'Average NPS from verified buyer reviews',
    labels: ['Support', 'Onboarding', 'Product', 'Value', 'Reliability'],
    bases: [72, 68, 81, 65, 78],
    chartKind: 'bar',
    unit: 'score',
    pattern: 'volatile',
  },
  {
    title: 'Cloud vs on-premise preference shift',
    subtitle: 'New deployments choosing cloud-native solutions',
    labels: ['2019', '2020', '2021', '2022', '2023', '2024', '2025'],
    bases: [52, 58, 64, 71, 78, 84, 91],
    chartKind: 'area',
    unit: 'percent',
    pattern: 'growth',
  },
  {
    title: 'Free trial to paid conversion',
    subtitle: 'SaaS benchmark conversion rates by category',
    labels: ['Productivity', 'Sales', 'Finance', 'HR', 'Dev tools'],
    bases: [14, 11, 8, 9, 16],
    chartKind: 'bar',
    unit: 'percent',
    pattern: 'volatile',
  },
  {
    title: 'Annual contract vs monthly billing',
    subtitle: 'Buyer preference for commitment length',
    labels: ['Monthly', 'Annual', 'Multi-year', 'Usage-based'],
    bases: [22, 48, 18, 12],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
  },
  {
    title: 'Security compliance as deal-breaker',
    subtitle: '% of buyers who disqualify vendors missing certifications',
    labels: ['SOC 2', 'GDPR', 'HIPAA', 'ISO 27001', 'PCI DSS'],
    bases: [78, 62, 45, 38, 52],
    chartKind: 'horizontal',
    unit: 'percent',
    pattern: 'ranked',
  },
  {
    title: 'Support ticket volume after go-live',
    subtitle: 'Weekly tickets - typical decline curve post-training',
    labels: ['Wk 1', 'Wk 2', 'Wk 4', 'Wk 6', 'Wk 8', 'Wk 12'],
    bases: [48, 38, 24, 16, 11, 6],
    chartKind: 'line',
    unit: 'count',
    pattern: 'decline',
  },
  {
    title: 'Mobile app usage among field teams',
    subtitle: 'Daily active users on mobile vs desktop',
    labels: ['Sales', 'Field service', 'Delivery', 'Inspection'],
    bases: [72, 88, 81, 76],
    bases2: [45, 32, 38, 41],
    chartKind: 'grouped',
    unit: 'percent',
    pattern: 'growth',
  },
  {
    title: 'Data migration accuracy rates',
    subtitle: 'Records migrated without errors or data loss',
    labels: ['Contacts', 'Transactions', 'Inventory', 'Employee', 'Documents'],
    bases: [96, 91, 88, 94, 82],
    chartKind: 'bar',
    unit: 'percent',
    pattern: 'ranked',
  },
  {
    title: 'User adoption in first 30 days',
    subtitle: 'Active users as % of licensed seats',
    labels: ['Day 7', 'Day 14', 'Day 21', 'Day 30'],
    bases: [28, 48, 62, 74],
    chartKind: 'area',
    unit: 'percent',
    pattern: 'growth',
  },
  {
    title: 'Pricing model preference by segment',
    subtitle: 'Which billing model SMB buyers prefer',
    labels: ['Per seat', 'Per usage', 'Flat rate', 'Freemium'],
    bases: [52, 18, 22, 8],
    chartKind: 'pie',
    unit: 'percent',
    pattern: 'share',
  },
]

export const CHART_PALETTES = [
  ['#0B2A6F', '#1D4ED8', '#3B82F6', '#60A5FA', '#93C5FD'],
  ['#F58220', '#EA580C', '#FB923C', '#FDBA74', '#FED7AA'],
  ['#0f766e', '#14b8a6', '#2dd4bf', '#5eead4', '#99f6e4'],
  ['#7c3aed', '#8b5cf6', '#a78bfa', '#c4b5fd', '#ddd6fe'],
  ['#be123c', '#e11d48', '#fb7185', '#fda4af', '#fecdd3'],
  ['#0B2A6F', '#F58220', '#14b8a6', '#7c3aed', '#be123c'],
] as const

export const SERIES_LABELS = [
  ['After implementation', 'Before implementation'],
  ['Cloud platform', 'Legacy system'],
  ['With automation', 'Manual process'],
  ['Current year', 'Previous year'],
  ['Top performers', 'Industry average'],
  ['AI-assisted', 'Human-only'],
] as const
